# Generated by Django 4.0.3 on 2022-03-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_mgp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradition', models.CharField(max_length=50, verbose_name='Tradition')),
                ('descr', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
