# Generated by Django 4.0.3 on 2022-04-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tradition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second Name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.IntegerField(max_length=11, verbose_name='Phone Number')),
            ],
        ),
    ]
