# Generated by Django 4.0.2 on 2022-05-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradition',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
