# Generated by Django 4.0.2 on 2022-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tradition_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradition',
            name='slug',
            field=models.SlugField(default='naruto', unique=True),
        ),
    ]
