# Generated by Django 4.0.3 on 2022-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_presidents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presidents',
            options={'verbose_name': 'Президент', 'verbose_name_plural': 'Президенттер'},
        ),
        migrations.AddField(
            model_name='presidents',
            name='image',
            field=models.CharField(default='disco', max_length=1500),
        ),
    ]
